### ISSUE TITLE
Home URL redirects to mozilla-hispano.org

### ISSUE THREAD

**Issue by bernimel** [mozillahispano/mozbuzz#38] opened 2013-05-02 16:23 UTC
Hi, 

When accesing https://www.mozilla-hispano.org/mozbuzz/ it redirects automatically to http://www.mozilla-hispano.org.

Best, 
Berni

**Comment by nukeador** [comment] 2013-05-02 20:40
I'm redirected to login and then to error 500.

@sveggiani was changing stuff yesterday.

**Comment by nukeador** [comment] 2013-05-02 20:44
I see this on mail log:

```
ImproperlyConfigured: SITE_URL incorrect. Settting is `https://www.mozilla-hispano.org/mozbuzz`, but request was `https://mozilla-hispano.org`


<WSGIRequest
path:/mozbuzz/browserid/login/,

```

**Comment by nukeador** [comment] 2013-05-05 22:57
@bernimel can you check it again please?

**Comment by bernimel** [comment] 2013-05-06 19:51
Checked and still happening @nukeador

**Comment by nukeador** [comment] 2013-05-06 21:23
I can't reproduce the problem. Can you check cleaning your cache and cookies and using another computer or browser?

**Comment by bernimel** [comment] 2013-05-06 21:34
I just log in (not Persona) and then the home of MozBuzz drives me to mozilla-hispano.org. It happens on all my desktop browsers (Firefox, Safari, Chrome), on iPhone and on iPad. 

If I log in with Persona it works. 

The thing is that some of our users don't have a PersonaID.

**Comment by nukeador** [comment] 2013-05-07 08:14
Let's just use persona for now till we found what's going on. If they are mozillians they should have a PersonaID, they are going to need it sooner or later.

And it's just 1 step to confirm the email and it's done.

**Comment by sebasmagri** [comment] 2013-05-11 14:42
Would we just drop non-Persona authentication on the site?

**Comment by bernimel** [comment] 2013-05-11 14:48
Would that mean that we cannot choose who's in? Would be that mean public access?

**Comment by sebasmagri** [comment] 2013-05-11 14:51
No. The current BrowserID setup for MozBuzz doesn't allow the automatic creation of new users. The users will still be created by an admin before they can login to the site.

**Comment by bernimel** [comment] 2013-05-11 15:07
Then it sounds good for me :) It's a good way to promote PersonaID. @nukeador what do you think?

**Comment by sebasmagri** [comment] 2013-05-11 15:19
To give more context to the discussion, recent changes in Django 1.5.x [0] include a new way of handling custom user models. Thus, the current mechanism used by Mozbuzz, `AUTH_PROFILE_MODULE`, is now deprecated in Django 1.5, and I'm almost sure this is why we're failing to authenticate with non-Persona login.

While we could migrate to the new Django's authentication model, it will represent schema and data migrations as stated by the Django docs.

```
Changing AUTH_USER_MODEL has a big effect on your database structure. It changes the tables
that are available, and it will affect the construction of foreign keys and many-to-many relationships.
If you intend to set AUTH_USER_MODEL, you should set it before running manage.py syncdb for
the first time.

If you have an existing project and you want to migrate to using a custom User model, you may
need to look into using a migration tool like South to ease the transition
```

OTOH, I agree with @bernimel that this is a good way to promote Persona, and, for example, webmaker apps and MDN use only Persona nowadays.

[0] https://docs.djangoproject.com/en/dev/topics/auth/customizing/#substituting-a-custom-user-model

**Comment by nukeador** [comment] 2013-05-11 15:25
I think only Persona login should be OK.

**Comment by bbotella** [comment] 2013-11-10 22:33
So, is this ticket still open? Are we going to just allow Persona login? If so, does this redirection matter?

**Comment by bernimel** [comment] 2013-11-10 22:54
I guess it's open because the redirection issue it's not fixed. I think that just allowing Persona is fine. If we do this, we should quit the user identification boxes for user&pass from the MozBuzz homepage.

**Comment by sebasmagri** [comment] 2014-01-26 01:15
Today we confirmed the new configuration options in BrowserID fix this so I'm closing this. This is fixed now in development.

**Closed as completed by sebasmagri** 2014-01-26 01:15 UTC
Labels: bug
